//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.SharpFitsIO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.SharpFitsIO.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis lengths must be set before writing the header..
        /// </summary>
        internal static string AxisLengthMustBeSet {
            get {
                return ResourceManager.GetString("AxisLengthMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot mark end of unit now..
        /// </summary>
        internal static string CannotMarkEnd {
            get {
                return ResourceManager.GetString("CannotMarkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read file opened for write..
        /// </summary>
        internal static string CannotReadFileOpenedForWrite {
            get {
                return ResourceManager.GetString("CannotReadFileOpenedForWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write file opened for read..
        /// </summary>
        internal static string CannotWriteFileOpenedForRead {
            get {
                return ResourceManager.GetString("CannotWriteFileOpenedForRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header is already read or written..
        /// </summary>
        internal static string HeaderAlreadyReadOrWritten {
            get {
                return ResourceManager.GetString("HeaderAlreadyReadOrWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header must be read or written before accessing data..
        /// </summary>
        internal static string HeaderMustBeReadOrWritten {
            get {
                return ResourceManager.GetString("HeaderMustBeReadOrWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header and associated values cannot be modified after the header has been written..
        /// </summary>
        internal static string HeaderNotMofiableAfterStart {
            get {
                return ResourceManager.GetString("HeaderNotMofiableAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns with varbinary(max), varchar(max), image and text are unsupported..
        /// </summary>
        internal static string MaxColumnsUnsupported {
            get {
                return ResourceManager.GetString("MaxColumnsUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream..
        /// </summary>
        internal static string UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported data type..
        /// </summary>
        internal static string UnsuportedDataType {
            get {
                return ResourceManager.GetString("UnsuportedDataType", resourceCulture);
            }
        }
    }
}
